name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14 # Use macOS Sonoma runners (latest)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app

    - name: Delete old Package.resolved
      run: |
        if [ -f Suwatte.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved ]; then
          rm Suwatte.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
        fi

    - name: List available schemes
      run: |
        xcodebuild -list -project Suwatte.xcodeproj

    - name: Resolve Swift Packages
      run: |
        xcodebuild -resolvePackageDependencies \
          -project Suwatte.xcodeproj

    - name: Build app
      run: |
        xcodebuild clean archive \
          -project Suwatte.xcodeproj \
          -scheme Suwatte \
          -configuration Release \
          -archivePath $PWD/build/Suwatte.xcarchive \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/Suwatte.xcarchive \
          -exportPath $PWD/build/export \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: Suwatte-IPA
        path: build/export
